# -*- coding: utf-8 -*-
"""phase 222.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Upm5muk00BqyyxqO_Wd2Xr5YA78uAGvu
"""

import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('modern_iphone_relations.csv', header=None, names=['Product1', 'Product2'])


G = nx.Graph()
G.add_edges_from(df.values)

plt.figure(figsize=(18, 12))
pos = nx.spring_layout(G, seed=42,k = 2, scale = 3)
nx.draw(G, pos, with_labels=True, node_size=5000, node_color='lightblue', font_size=15,font_weight ='bold')
plt.title("iPhone Products Network", fontsize=14)
plt.show()


iphone_models = [node for node in G.nodes if "iPhone" in node]

print("Most connected product for each iPhone model:\n")
for model in iphone_models:
    neighbors = list(G.neighbors(model))
    if not neighbors:
        print(f"{model}: No related products.")
        continue

    most_related = sorted(neighbors, key=lambda x: G.degree(x), reverse=True)[0]
    print(f"{model} ➜ {most_related} (connections: {G.degree(most_related)})")

import networkx as nx
import matplotlib.pyplot as plt

graph1 = nx.Graph()


shared_labels = {
    3: "Case",
    4: "Protector",
    5: "AirPods",
    6: "Charger"
}


orders1 = [
    [1, 3, 4],
    [2, 3, 5],
    [1, 5, 6],
    [2, 4, 6],
    [1, 2],
    [3, 4, 5, 6]
]


for order in orders1:
    for i in range(len(order)):
        for j in range(i+1, len(order)):
            a, b = order[i], order[j]
            if graph1.has_edge(a, b):
                graph1[a][b]['count'] += 1
            else:
                graph1.add_edge(a, b, count=1)

labels1 = {
    1: "iPhone 13",
    2: "iPhone 14",
    **shared_labels
}


graph2 = nx.Graph()


orders2 = [
    [7, 3, 5],
    [8, 4, 6],
    [7, 8],
    [3, 4, 5, 6]
]


for order in orders2:
    for i in range(len(order)):
        for j in range(i+1, len(order)):
            a, b = order[i], order[j]
            if graph2.has_edge(a, b):
                graph2[a][b]['count'] += 1
            else:
                graph2.add_edge(a, b, count=1)

labels2 = {
    7: "iPhone 15",
    8: "iPhone 12",
    **shared_labels
}

fig, axes = plt.subplots(1, 2, figsize=(16, 7))


pos1 = nx.spring_layout(graph1, seed=42)
nx.draw(graph1, pos1, ax=axes[0], with_labels=False, node_size=500, node_color='lightblue', width=[graph1[u][v]['count'] for u, v in graph1.edges()])
nx.draw_networkx_labels(graph1, pos1, labels=labels1, ax=axes[0], font_size=11)
axes[0].set_title("Network: iPhone 13 & 14")
axes[0].axis('off')


pos2 = nx.spring_layout(graph2, seed=99)
nx.draw(graph2, pos2, ax=axes[1], with_labels=False, node_size=500, node_color='lightgreen', width=[graph2[u][v]['count'] for u, v in graph2.edges()])
nx.draw_networkx_labels(graph2, pos2, labels=labels2, ax=axes[1], font_size=11)
axes[1].set_title("Network: iPhone 12 & 15")
axes[1].axis('off')

plt.suptitle("iPhone Networks Bought Together (Separate Networks)", fontsize=14)
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# إنشاء بيانات عشوائية مشابهة للصورة
np.random.seed(42)
n_points = 20
x = np.random.uniform(0, 2, n_points)
y = np.random.uniform(0, 2, n_points)
values = np.random.uniform(0, 1, n_points)

# إنشاء DataFrame
df = pd.DataFrame({'X': x, 'Y': y, 'Value': values})

# إنشاء الشكل
plt.figure(figsize=(10, 8))

# رسم سحابة النقاط
scatter = sns.scatterplot(
    data=df,
    x='X',
    y='Y',
    size='Value',
    hue='Value',
    sizes=(50, 300),  # نطاق أحجام النقاط
    palette='viridis',
    alpha=0.7,
    edgecolor='black',
    linewidth=0.5
)

# إضافة تسميات للنقاط
for i in range(len(df)):
    plt.text(
        x=df.X[i]+0.05,
        y=df.Y[i]+0.05,
        s=f"{df.Value[i]:.2f}",
        fontsize=8,
        ha='center'
    )

# إضافة خطوط للعلاقات بين النقاط القريبة
threshold = 0.5  # عتبة المسافة لعرض الخطوط
for i in range(len(df)):
    for j in range(i+1, len(df)):
        distance = np.sqrt((df.X[i]-df.X[j])**2 + (df.Y[i]-df.Y[j])**2)
        if distance < threshold:
            plt.plot(
                [df.X[i], df.X[j]],
                [df.Y[i], df.Y[j]],
                color='gray',
                linestyle='--',
                alpha=0.4,
                linewidth=0.7
            )

# تحسين العناوين والتنسيق
plt.title('Relationship Cloud with Distance Connections', pad=20, fontsize=14)
plt.xlabel('X-axis', fontsize=10)
plt.ylabel('Y-axis', fontsize=10)
plt.grid(True, alpha=0.2)
plt.xlim(0, 2)
plt.ylim(0, 2)

# إضافة شريط الألوان
plt.colorbar(scatter.collections[0], label='Value')
plt.legend(title='Value', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()