# -*- coding: utf-8 -*-
"""phase 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Upm5muk00BqyyxqO_Wd2Xr5YA78uAGvu
"""

import networkx as nx
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('modern_iphone_relations.csv', header=None, names=['Product1', 'Product2'])


G = nx.Graph()
G.add_edges_from(df.values)

plt.figure(figsize=(18, 12))
pos = nx.spring_layout(G, seed=42,k = 2, scale = 3)
nx.draw(G, pos, with_labels=True, node_size=5000, node_color='lightblue', font_size=15,font_weight ='bold')
plt.title("iPhone Products Network", fontsize=14)
plt.show()


iphone_models = [node for node in G.nodes if "iPhone" in node]

print("Most connected product for each iPhone model:\n")
for model in iphone_models:
    neighbors = list(G.neighbors(model))
    if not neighbors:
        print(f"{model}: No related products.")
        continue

    most_related = sorted(neighbors, key=lambda x: G.degree(x), reverse=True)[0]
    print(f"{model} ➜ {most_related} (connections: {G.degree(most_related)})")

